import 'package:test_app/models/details.dart';

List<Details> describeData(String userGroup){
  List<Details>details=[];
  if(userGroup=="Alpha 1 Male"){
    
    details.add(Details(image: "assets/images/humble_guy.png", title:"1. The Grounded and Humble Guy", desc:"The moment you set your eyes on him, you know he is kind. He is not a pushover and not easy to win. He is grounded, self-assured and competent. When you meet him, he might be quiet or make small talk. But after little conversations, the relationship sails smoothly. He can be reflexively aggressive when the situation demands it. If criticism is needed, he does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_guy.png", title:"The Smart Guy", desc:"He does not believe in beating around the bush. He will always give you the facts as they are and wont twist them, even if it requires bluntness on their part. He believes that open honest conversations are the roots of a solid relationship. He might not open up in text about his internal feelings. "));
    details.add(Details(image: "assets/images/dynamic_purposeful_guy.png", title:"The Dynamic and Purposeful Guy", desc:"He believes in hard work and can take responsibilities and get the job done. He is a person of well built opinions and always open to new experiences and mindsets. He is a selfless encouraging person, always making plans and staying involved. He is willing to take calculated and intelligent risks. In extreme circumstances, he is composed, decisive and quick to react."));
    details.add(Details(image: "assets/images/Charming_guy.png", title:"The Charming Guy", desc:"Spending time with him is enriching and energising. He is confident and good natured under his hard exterior. He lets you be comfortable and sure in your truest self. When you talk, you are always his focus of attention, he listens. He makes you feel seen and validates you. He is less inclined to texting and usually keeps his chats short."));
    details.add(Details(image: "assets/images/Alluring_Guy.png", title:"The Alluring Guy", desc:"He celebrates your achievements and helps you shine in the spotlight. You can tell him your deepest insecurities without shame, fear or discomfort. Your issues and situations receive equal focus as his own. He makes good listeners and secret keepers. He points out the faults in the approach, not in you. These qualities, coupled with his good nature, make him a good caring one."));
     
  };

   if(userGroup=="Alpha 2 Male"){
    
    details.add(Details(image: "assets/images/humble_guy.png", title:"The Humble and Grounded Guy", desc:"The moment you set your eyes on him, you know he is a keeper. He is grounded, self-assured and competent. When you meet him, he might be quiet or make small talk. He can be reflexively aggressive when the situation demands it. If criticism is needed, he does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_guy.png", title:"The Smart Guy", desc:"He does not believe in beating around the bush.  He will always give you the facts as they are and wont twist them, even if it requires bluntness on their part. He believes that open honest conversations are the roots of a solid relationship. He might not open up in text about his internal feelings."));
    details.add(Details(image: "assets/images/dynamic_purposeful_guy.png", title:"The Dynamic Guy", desc:"He believes in hard work and can take responsibilities and get the job done. He is a person of well built opinions. He is self-reliant and treats other people with respect and consideration. He is honest and straightforward. He is willing to take calculated and intelligent risks. In extreme circumstances, he is composed, decisive and quick to react."));
    details.add(Details(image: "assets/images/Charming_guy.png", title:"The Charming  Guy", desc:"He constantly texts you, showers attention, makes you feel wanted. You also want to make him happy. He lets you be comfortable and sure in your truest self. When you talk, you are always his focus of attention, he listens. He makes you feel seen and validates you but not all the time. It feels like he depends on you. He is true to his word and believes in keeping his promises."));
    details.add(Details(image: "assets/images/self_obssessed_Guy.png", title:"The Self Obsessed Guy", desc:"He thinks that he is always right and everything should be done according to his methods. Even if you know that it is his fault, he will never expect you to ask him to say sorry. If something happens which he does not approve of, everything goes down the drain. Somehow, he makes everything about himself. It started with benign teasing, but it might turn to mean and hurtful and might make you lose confidence in yourself slowly."));
      
  };

  if(userGroup=="Alpha 3 Male"){
    
    details.add(Details(image: "assets/images/humble_guy.png", title:"The Humble and Grounded Guy", desc:"The moment you set your eyes on him, you know he is not a pushover. He is grounded, self-assured and competent. You just met him and he tells you about his most secret vulnerabilities, making you feel you are special and he trusts you and therefore he gains his trust in return. He can be reflexively aggressive when the situation demands it."));
    details.add(Details(image: "assets/images/dynamic_purposeful_guy.png", title:"The Dynamic Guy", desc:"He believes in hard work and can take responsibilities and get the job done. In extreme circumstances, he is composed, decisive and quick to react. He is always making plans and staying involved. He celebrates your achievements and helps you shine in the spotlight."));
    details.add(Details(image: "assets/images/Charming_guy.png", title:"The Charming Guy", desc:"Spending time with him is enriching and energising. He is confident and good natured under his hard exterior. He lets you be comfortable and sure in your truest self. When you talk, you are always his focus of attention, he listens and keeps secrets."));
    details.add(Details(image: "assets/images/charismatic_Guy.png", title:"The Charismatic Guy", desc:"He questions you and allows you to first speak, and tries to understand your thinking. As you get to know him deeper, you find that he might claim to know more than you, he rejects your opinions sometimes. He is good at spinning words. His actions do not correspond to his words. Sometimes he never means what he is saying, he might also deny whenever he says something problematic."));
    details.add(Details(image: "assets/images/manipulative_guy.png", title:"The Manipulative Guy", desc:"Under the guise of joking, he makes rude inconsiderate statements. He constantly criticises you for the smallest things. With time, you will be affected by this constant nagging. If you even try to voice your concerns, he will lie to you or blame you, to make the friendship go on. He is sensitive to others feelings, but sometimes he might make dramatic baseless statements during confrontations and he might use your feelings against you."));
     
  };

   if(userGroup=="Alpha 4 Male"){
    
    details.add(Details(image: "assets/images/humble_guy.png", title:"The Humble and Grounded Guy", desc:"The moment you set your eyes on him, you know he is not a pushover. He is grounded, self-assured and competent. You just met him, he constantly texts you, showers attention, and he tells you about his most secret vulnerabilities, making you feel you are special and he trusts you and therefore he gains his trust in return. You might also want to make him happy."));
    details.add(Details(image: "assets/images/dynamic_purposeful_guy.png", title:"The Dynamic Guy", desc:"He believes in hard work and can take responsibilities and get the job done. In extreme circumstances, he is composed, decisive and quick to react.He is a strategist, always making plans and staying involved. He always pursues compliments but lacks empathy for others in certain situations. He lets you be comfortable and sure in your truest self."));
    details.add(Details(image: "assets/images/charismatic_Guy.png", title:"The Charismatic Guy", desc:"He questions you and allows you to first speak, and tries to understand your thinking. As you get to know him deeper, you find that he might claim to know more than you, he rejects your opinions sometimes. He is good at spinning words. His actions do not correspond to his words.Sometimes he never means what he is saying, he might also deny whenever he says something problematic."));
    details.add(Details(image: "assets/images/self_obssessed_Guy.png", title:"The Self Obsessed Guy", desc:"He thinks that he is always right and everything should be done according to his methods. Even if you know that it is his fault, he will never expect you to ask him to say sorry. If something happens which he does not approve of, everything goes down the drain. Somehow, he makes everything about himself. It started with benign teasing, but it might turn to mean and hurtful and might make you lose confidence in yourself slowly."));
    details.add(Details(image: "assets/images/manipulative_guy.png", title:"The Manipulative Guy", desc:"Under the guise of joking, he makes rude inconsiderate statements. He constantly criticises you for the smallest things. With time, you will be affected by this constant nagging. If you even try to voice your concerns, he will lie to you or blame you, to make the friendship go on. He is sensitive to others feelings, but sometimes he might make dramatic baseless statements during confrontations, he might use your feelings against you."));
       
  };

   if(userGroup=="Alpha 5 Male"){
    
    details.add(Details(image: "assets/images/charismatic_Guy.png", title:"The Charismatic Guy", desc:"It looks like he is very pleasant when you first meet him, so attentive. His presence, trust and charisma disarm you. He is self-assured, competent and proud. He believes in hard work and doing the right thing. He is a person of well built opinions but always open to new experiences and mindsets. He is only trying to discover ways of gaining your confidence. If criticism is needed, he does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_guy.png", title:"The Smart Guy", desc:"He is honest and straightforward. He will always give you the facts as they are and wont twist them, even if it requires bluntness on their part. You never truly know what is happening in his brain, you are always left guessing. He believes that open honest conversations are the roots of a solid relationship. He might not open up in text about his internal feelings."));
    details.add(Details(image: "assets/images/dynamic_purposeful_guy.png", title:"The Dynamic Guy", desc:"He celebrates your achievements and helps you shine in the spotlight. He values your opinions even if they may vary from his own. He does not shame you for your interests. Instead, he is your ally in all activities you wish to pursue. He makes plans with you. In extreme circumstances, he is composed, decisive and quick to react."));
    details.add(Details(image: "assets/images/Charming_guy.png", title:"The Charming Guy", desc:"Spending time with him is enriching and energising. He is confident and good natured under his hard exterior. He lets you be comfortable and sure in your truest self. When you talk, you are always his focus of attention, he listens. He makes you feel seen and validates you, but depending upon his moods too, he sometimes is quite unresponsive and his true emotions rarely appear."));
    details.add(Details(image: "assets/images/impulsive_guy.png", title:"The Impulsive Guy", desc:"After relations begin to lose, things start to shift. His surprise ideas at the beginning now appear more impulsive. Sometimes he is late, and he either deflects or quotes work reasons if you question him where he was. He is also more upset, getting irritated for the smallest of reasons. He does not express guilt for his mistakes and faults, he never apologises. After every encounter, you are left slightly drained."));
        
  };

   if(userGroup=="Alpha 6 Male"){
    
    details.add(Details(image: "assets/images/charismatic_Guy.png", title:"The Charismatic Guy", desc:"It looks like he is very pleasant when you first meet him, so attentive. His presence, trust and charisma disarm you. He is self-obsessed, competent and proud. He is a person of well built opinions but always open to new experiences and mindsets. He is only trying to discover ways of gaining your confidence and you might certainly want to make him happy.If criticism is needed, he does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_guy.png", title:"The Smart Guy", desc:"He is honest and straightforward. He will always give you the facts as they are and wont twist them, even if it requires bluntness on their part.He constantly texts you, showers attention, makes you feel wanted. You never truly know what is happening in his brain, you are always left guessing. He values your opinions even if they may vary from his own. He might not open up in text about his internal feelings. "));
    details.add(Details(image: "assets/images/dynamic_purposeful_guy.png", title:"The Dynamic Guy", desc:"He celebrates your achievements and helps you shine in the spotlight. In extreme circumstances, he is composed, decisive and quick to react. Your issues and situations receive equal focus as his own, but depending upon his  moods too, he sometimes is quite unresponsive and his true emotions rarely appear. Sometimes his emotions feel fake, he pretends that he is interested with your things and you do not feel seen or understood when you are with him."));
    details.add(Details(image: "assets/images/impulsive_guy.png", title:"The Impulsive Guy", desc:"After relations begin to lose, things start to shift. His surprise ideas at the beginning now appear more impulsive. Sometimes he is late, and he either deflects or quotes work reasons if you question him where he was. He is also more upset, getting irritated for the smallest of reasons. He does not express guilt for his mistakes and faults, he never apologises. After every encounter, you are left slightly drained."));
    details.add(Details(image: "assets/images/self_obssessed_Guy.png", title:"The Self Obsessed Guy", desc:"He thinks that he is always right and everything should be done according to his methods. Even if you know that it is his fault, he will never expect you to ask him to say sorry. If something happens which he does not approve of, everything goes down the drain. Somehow, he makes everything about himself. It started with benign teasing, but it might turn to mean and hurtful and might make you lose confidence in yourself slowly."));
        
  };

   if(userGroup=="Alpha 7 Male"){
    
    details.add(Details(image: "assets/images/charismatic_Guy.png", title:"The Charismatic Guy", desc:"It looks like he is very pleasant when you first meet him, so attentive. His presence, trust and charisma disarm you. He is self-assured, competent and proud. You just met him and he tells you about his most secret vulnerabilities, he questions you and allows you to first speak, and tries to understand your thinking,making you feel you are special and he trusts you and only for trying to discover ways of gaining your confidence."));
    details.add(Details(image: "assets/images/smart_guy.png", title:"The Smart Guy", desc:"He always claims to know more than you, he rejects your opinions sometimes. You never truly know what is happening in his brain, you are always left guessing. He is good at spinning words. His actions do not correspond to his words. Sometimes he never means what he is saying; he might also deny whenever he says something problematic."));
    details.add(Details(image: "assets/images/dynamic_purposeful_guy.png", title:"The Dynamic Guy", desc:"He celebrates your achievements and helps you shine in the spotlight. Your issues and situations receive equal focus as his own, but depending upon his  moods too, he sometimes is quite unresponsive and his true emotions rarely appear. Sometimes his emotions feel fake, he pretends that he is interested with your things and you do not feel seen or understood when you are with him."));
    details.add(Details(image: "assets/images/impulsive_guy.png", title:"The Impulsive Guy", desc:"After relations begin to lose, things start to shift. His surprise ideas at the beginning now appear more impulsive. Sometimes he is late, and he either deflects or quotes work reasons if you question him where he was. He is also more upset, getting irritated for the smallest of reasons. He does not express guilt for his mistakes and faults, he never apologises. After every encounter, you are left slightly drained."));
    details.add(Details(image: "assets/images/manipulative_guy.png", title:"The Manipulative Guy", desc:"Under the guise of joking, he makes rude inconsiderate statements. He constantly criticises you for the smallest things. With time, you will be affected by this constant nagging. If you even try to voice your concerns, he will lie to you or blame you, to make the friendship go on. He is sensitive to others feelings, but sometimes he might make dramatic baseless statements during confrontations, he might use your feelings against you."));
   
  };

   if(userGroup=="Beta 1 Male"){
    
    details.add(Details(image: "assets/images/mesmerising_guy.png", title:"The Mesmerising Guy", desc:"When you meet him, He is all in his own world. He is direct and efficient. He texts you firmly, compliments you, things begin to look like a fairy tale, making you feel wanted. This makes you want to keep pleasing him and everything is happy in paradise. He prioritises his goals and ambitions. He will always tell you the truth, even if it means being blunt."));
    details.add(Details(image: "assets/images/flamboyant_guy.png", title:"The Flamboyant Guy", desc:"He has strong beliefs but is always open to new experiences, he sees all the sides of every situation.  He asks your opinions while making important decisions and pays heed to your advice. He is direct with his thoughts on any ideas being discussed. Instead, he is your partner in all of your endeavours. He is an agreeable easy-going person and fun to be around."));
    details.add(Details(image: "assets/images/hotshot_guy.png", title:"The Hotshot Guy", desc:"He is calm, decisive, and fast in high-pressure situations. When speaking with him, you are always treated as an equal. He never disregards an idea outright if you present it to him but if it is against him then he constantly picks on you. This will begin with harmless teasing, but afterwards, It is mean and hurtful. He is constantly fishing for compliments. All conversations with him ends up becoming about him. It is always his achievements, his situations."));
    details.add(Details(image: "assets/images/narcissist_guy.png", title:"The Narcissist Guy", desc:"While texting he may twist your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. He can not be handled in texting, to understand him you better have to hear his tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, he lash out and become aggressive. He may go as far as to destroy your reputation to save his own."));
    details.add(Details(image: "assets/images/gaslighter_guy.png", title:"The Gaslighter Guy", desc:"Gaslighting is his ultimate weapon, which brings down your self-esteem, thereby giving him an inflated sense of self. He believes he is right about everything. He will never be the one who apologises, even if you know it is his fault. When you are with him, you do not feel seen or understood. He will panic and try to fool you with kind words, promising you that he will change, become better."));
      
  };

  if(userGroup=="Beta 2 Male"){
    
    details.add(Details(image: "assets/images/mesmerising_guy.png", title:"The Mesmerising Guy", desc:"When you meet him, He is all in his own world. He is easy to talk to and has a pleasant attitude. He texts you firmly, compliments you. You have only just met him and five minutes later He is telling you his most secret vulnerabilities, making you believe you are special and that he trusts you. He asks you questions and lets you speak up first, trying to understand your mindset. He is the pacifist in any discussion. He consistently tries to be on the same page with you."));
    details.add(Details(image: "assets/images/flamboyant_guy.png", title:"The Flamboyant Guy", desc:"He is organised, focused and driven. He is an agreeable easy-going person and fun to be around. He congratulates you on your accomplishments as if they were his own and encourages you to do the same. He is empathic, which makes him an attentive listener and maintains honest relationships. He can adequately handle responsibilities and get the job done."));
    details.add(Details(image: "assets/images/hotshot_guy.png", title:"The Hotshot Guy", desc:"Also if you make a mistake, he does not chastise you for it. Instead, he will go to great efforts to assist you in resolving the issue. Sometimes he bullies you which can take varied forms, he always knows more than you. He will either lie and or push the blame on you, calling you crazy. He makes rude inconsiderate statements under the guise of I am kidding but, It is meant to cause offence. He denies he ever said something, even though you have proof."));
    details.add(Details(image: "assets/images/machiavelliant_guy.png", title:"The Machiavellian Guy", desc:"He criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through his teeth is second nature to them. His actions do not match his words. During confrontations, he uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, he gives you the silent treatment. Even if you were not the one at fault, his silence shifts the weight of his behaviour on you. He excellently manipulates you, pulling your strings like a puppet, because he knows what makes you tick."));
    details.add(Details(image: "assets/images/imposter_guy.png", title:"The Imposter Guy", desc:"He is aware of the power of words and is cautious while using them. His comments are presented in a kind tone. While texting he twists your words and plays with it, changing the narrative and easily manipulating you with texts. He spins your thoughts, taking them out of context. Every text you send feels like a step on thin ice. He can not be handled in texting, to understand him you better have to hear his tone of saying."));
        
  };

  if(userGroup=="Beta 3 Male"){
    
    details.add(Details(image: "assets/images/mesmerising_guy.png", title:"The Mesmerising Guy", desc:"When you meet him, He is all in his own world. He texts you firmly, compliments you, things begin to look like a fairy tale, making you feel wanted. This makes you want to keep pleasing him and everything is happy in paradise. You have only just met him and five minutes later He is telling you his most secret vulnerabilities, making you believe you are special and that he trusts you. He asks you questions and lets you speak up first, trying to understand your mindset."));
    details.add(Details(image: "assets/images/hotshot_guy.png", title:"The Hotshot Guy", desc:"He is organised, focused and driven. He is an agreeable easy-going person and fun to be around. He is an attentive listener and maintains honest relationships. Sometimes he bullies you which can take varied forms, he always knows more than you. He will either lie or push the blame on you, calling you crazy. He makes rude inconsiderate statements under the guise of I am kidding but, It is meant to cause offence. He denies he ever said something, even though you have proof."));
    details.add(Details(image: "assets/images/narcissist_guy.png", title:"The Narcissist Guy", desc:"While texting he may twist your words and plays with it, changing the narrative and easily manipulating you with texts. He spins your thoughts, taking them out of context. Every text you send feels like a step on thin ice. He can not be handled in texting, to understand him you better have to hear his tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, he lash out and become aggressive, calling you names. He may go as far as to destroy your reputation to save his own."));
    details.add(Details(image: "assets/images/machiavelliant_guy.png", title:"The Machiavellian Guy", desc:"He criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through his teeth is second nature to them. His actions do not match his words. During confrontations, he uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, he gives you the silent treatment. Even if you were not the one at fault, his silence shifts the weight of his behaviour on you. He excellently manipulates you, pulling your strings like a puppet, because he knows what makes you tick."));
    details.add(Details(image: "assets/images/gaslighter_guy.png", title:"The Gaslighter Guy", desc:"Gaslighting is his ultimate weapon, which brings down your self-esteem, thereby giving him an inflated sense of self. He believes he is right about everything. He will never be the one who apologises, even if you know it is his fault. When you are with him, you do not feel seen or understood. It feels like all he has is just you. He will panic and try to fool you with kind words, promising you that he will change, become better."));
     
  };

 
   if(userGroup=="Beta 4 Male"){
    
    details.add(Details(image: "assets/images/generous_guy.png", title:"The Generous Guy", desc:"When you first meet him, he seems like He is so charming, so attentive. He has strong beliefs but is always open to new experiences, he sees all the sides of every situation. In the beginning he can be a little difficult to talk to, but has a pleasant attitude. The relationship might, however, smooth out after that rocky stretch. He is the pacifist in any discussion. He listens to your viewpoints, even if they differ from his own, he is just trying to find ways to gain your trust."));
    details.add(Details(image: "assets/images/flamboyant_guy.png", title:"The Flamboyant Guy", desc:"There is a presence about him, his confidence, self-assuredness and charm disarm you. He pretends to be good natured, makes plans with you, makes you like him in the beginning. He congratulates you on your accomplishments as if they were his own and encourages you to do the same. You never really know what is going on in his head which always keeps you guessing. Once he is sure, you trust him completely, he becomes the parasite himself and you become his host."));
    details.add(Details(image: "assets/images/hotshot_guy.png", title:"The Hotshot Guy", desc:"He is aware of the power of words and is cautious while using them. His comments are presented in a kind tone. While texting he twists your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. He can not be handled in texting, to understand him you better have to hear his tone of saying."));
    details.add(Details(image: "assets/images/proud_guy.png", title:"The Proud Guy", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes He is late and when you ask him where he was, he either deflects or cites work reasons. He also has these moods nowadays, his temper flying at the tiniest of reasons. His earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. He shows no guilt over his mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/imposter_guy.png", title:"The Imposter Guy", desc:"He changes the subject when you ask more about him. Even after spending all this time, you never truly know what He is actually like. He is cold and inconsiderate to the feelings of other people around him. He lacks discipline and you feel like He is going down and dragging you with him. In the past, he says he has had multiple partners but none of them lasted long. he is receptive to your feedback and grateful for them."));
       
  };

   if(userGroup=="Beta 5 Male"){
    
    details.add(Details(image: "assets/images/generous_guy.png", title:"The Generous Guy", desc:"When you first meet him, he seems like He is so charming, so attentive. He texts you constantly, flatters you with compliments, things begin to look like a fairy tale, making you feel wanted. This makes you want to keep pleasing him and everything is happy in paradise. There is a presence about him, his confidence and charm disarm you. Once he is sure, you trust him completely, he becomes the parasite himself and you become his host."));
    details.add(Details(image: "assets/images/proud_guy.png", title:"The Proud Guy", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes He is late and when you ask him where he was, he either deflects or cites work reasons. He also has these moods nowadays, his temper flying at the tiniest of reasons. His earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. He shows no guilt over his mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/imposter_guy.png", title:"The Imposter Guy", desc:"He changes the subject when you ask more about him. Even after spending all this time, you never truly know what He is actually like. He is cold and inconsiderate to the feelings of other people around him. He lacks discipline and you feel like He is going down and dragging you with him. In the past, he says he has had multiple partners but none of them lasted long. he is receptive to your feedback and grateful for them."));
    details.add(Details(image: "assets/images/narcissist_guy.png", title:"The Narcissist Guy", desc:"While texting he twists your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. He can not be handled in texting, to understand him you better have to hear his tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, he lash out and become aggressive, calling you names. He may go as far as to destroy your reputation to save his own."));
    details.add(Details(image: "assets/images/gaslighter_guy.png", title:"The Gaslighter Guy", desc:"Gaslighting is his ultimate weapon, which brings down your self-esteem, thereby giving him an inflated sense of self. He believes he is right about everything. He will never be the one who apologises, even if you know it is his fault. When you are with him, you do not feel seen or understood. It feels like all he has is just you. He will panic and try to fool you with kind words, promising you that he will change, become better."));
        
  };

  if(userGroup=="Beta 6 Male"){
    
    details.add(Details(image: "assets/images/generous_guy.png", title:"The Generous Guy", desc:"When you first meet him, he seems like He is so charming, so attentive. He is easy to talk to and has a pleasant attitude. He flatters you with compliments. You have only just met him and five minutes later He is telling you his most secret vulnerabilities, making you believe you are special and that he trusts you, he is just trying to find ways to gain your trust. He asks you questions and lets you speak up first, trying to understand your mindset."));
    details.add(Details(image: "assets/images/flamboyant_guy.png", title:"The Flamboyant Guy", desc:"There is a presence about him, his confidence, self-assuredness and charm disarm you. He pretends to be good natured, makes plans with you, makes you like him in the beginning. He congratulates you on your accomplishments as if they were his own and encourages you to do the same. You never really know what is going on in his head which always keeps you guessing. Once he is sure, you trust him completely, he becomes the parasite himself and you become his host."));
    details.add(Details(image: "assets/images/proud_guy.png", title:"The Proud Guy", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes He is late and when you ask him where he was, he either deflects or cites work reasons. He also has these �moods� nowadays, his temper flying at the tiniest of reasons. His earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. He shows no guilt over his mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/imposter_guy.png", title:"The Imposter Guy", desc:"He changes the subject when you ask more about him. Even after spending all this time, you never truly know what He is actually like. He is cold and inconsiderate to the feelings of other people around him. He lacks discipline and you feel like He is going down and dragging you with him. In the past, he says he has had multiple partners but none of them lasted long. he is receptive to your feedback and grateful for them."));
    details.add(Details(image: "assets/images/machiavelliant_guy.png", title:"The Machiavellian Guy", desc:"He criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through his teeth is second nature to them. His actions do not match his words. During confrontations, He uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, he gives you the silent treatment. Even if you were not the one at fault, his silence shifts the weight of his behaviour on you. He excellently manipulates you, pulling your strings like a puppet, because he knows what makes you tick."));
     
  };

  if(userGroup=="Beta 7 Male"){
    
    details.add(Details(image: "assets/images/generous_guy.png", title:"The Generous Guy", desc:"When you first meet him, he seems like He is so charming, showering you with attention. He texts you constantly, flatters you with compliments, things begin to look like a fairy tale, making you feel wanted and everything is happy in paradise. You have only just met him and five minutes later He is telling you his most secret vulnerabilities, he asks you questions and lets you speak up first, making you believe you are special, he is just trying to find ways to gain your trust. Once he is sure, you trust him completely, he becomes the parasite himself and you become his host."));
    details.add(Details(image: "assets/images/proud_guy.png", title:"The Proud Guy", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes He is late and when you ask him where he was, he either deflects or cites work reasons. He also has these moods nowadays, his temper flying at the tiniest of reasons. His earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. He shows no guilt over his mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/machiavelliant_guy.png", title:"The Machiavellian Guy", desc:"He criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through his teeth is second nature to them. His actions do not match his words. During confrontations, He uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, he gives you the silent treatment. Even if you were not the one at fault, his silence shifts the weight of his behaviour on you. He excellently manipulates you, pulling your strings like a puppet, because he knows what makes you tick."));
    details.add(Details(image: "assets/images/narcissist_guy.png", title:"The Narcissist Guy", desc:"While texting he twists your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. He can not be handled in texting, to understand him you better have to hear his tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, he lash out and become aggressive, calling you names. He may go as far as to destroy your reputation to save his own."));
    details.add(Details(image: "assets/images/gaslighter_guy.png", title:"The Gaslighter Guy", desc:"Gaslighting is his ultimate weapon, which brings down your self-esteem, thereby giving him an inflated sense of self. He believes he is right about everything. He will never be the one who apologises, even if you know it is his fault. When you are with him, you do not feel seen or understood. It feels like all he has is just you. He will panic and try to fool you with kind words, promising you that he will change, become better."));
    
  };

   if(userGroup=="Alpha 1 Female"){
    
    details.add(Details(image: "assets/images/humble_girl.png", title:"The Humble and Grounded Girl", desc:"The moment you set your eyes on her, you know sHe is kind. She is not a pushover and not easy to win. She is grounded, self-assured and competent. When you meet her, she might be quiet or make small talk. But after little conversations, the relationship sails smoothly. She can be reflexively aggressive when the situation demands it. If criticism is needed, she does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_girl.png", title:"The Smart Girl", desc:"She does not believe in beating around the bush. She will always give you the facts as they are and wont twist them, even if it requires bluntness on their part. She believes that open honest conversations are the roots of a solid relationship. She might not open up in text about her internal feelings."));
    details.add(Details(image: "assets/images/Dynamic_and_Purposeful_Girl.png", title:"The Dynamic and Purposeful Girl", desc:"She believes in hard work and can take responsibilities and get the job done. She is a person of well built opinions and always open to new experiences and mindsets. She is a selfless encouraging person, always making plans and staying involved. SHe is willing to take calculated and intelligent risks. In extreme circumstances, she is composed, decisive and quick to react."));
    details.add(Details(image: "assets/images/charming_Girl.png", title:"The Charming Girl", desc:"Spending time with her is enriching and energising. She is confident and good natured under her hard exterior. She lets you be comfortable and sure in your truest self. When you talk, you are always her focus of attention, she listens. She makes you feel seen and validates you. She is less inclined to texting and usually keeps her chats short."));
    details.add(Details(image: "assets/images/Alluring_Girl.png", title:"The Alluring Girl", desc:"She celebrates your achievements and helps you shine in the spotlight. You can tell her your deepest insecurities without shame, fear or discomfort. Your issues and situations receive equal focus as her own. She makes good listeners and secret keepers. She points out the faults in the approach, not in you. These qualities, coupled with her good nature, make him a good caring one."));
   
  };

    if(userGroup=="Alpha 2 Female"){
    
    details.add(Details(image: "assets/images/humble_girl.png", title:"The Humble and Grounded Girl", desc:"The moment you set your eyes on her, you know she is a keeper. She is grounded, self-assured and competent. When you meet her, she might be quiet or make small talk. She can be reflexively aggressive when the situation demands it. If criticism is needed, she does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_girl.png", title:"The Smart Girl", desc:"She does not believe in beating around the bush.  She will always give you the facts as they are and wont twist them, even if it requires bluntness on their part. She believes that open honest conversations are the roots of a solid relationship. She might not open up in text about her internal feelings."));
    details.add(Details(image: "assets/images/Dynamic_and_Purposeful_Girl.png", title:"The Dynamic Girl", desc:"She believes in hard work and can take responsibilities and get the job done. She is a person of well built opinions. She is self-reliant and treats other people with respect and consideration. She is honest and straightforward. She is willing to take calculated and intelligent risks. In extreme circumstances, she is composed, decisive and quick to react."));
    details.add(Details(image: "assets/images/charming_Girl.png", title:"The Charming Girl", desc:"She constantly texts you, showers attention, makes you feel wanted. You also want to make him happy. She lets you be comfortable and sure in your truest self. When you talk, you are always her focus of attention, she listens. She makes you feel seen and validates you but not all the time. It feels like she depends on you. She is true to her word and believes in keeping her promises."));
    details.add(Details(image: "assets/images/self_obssessed_Girl.png", title:"The Self Obsessed Girl", desc:"She thinks that she is always right and everything should be done according to her methods. Even if you know that it is her fault, she will never expect you to ask her to say sorry. If something happens which she does not approve of, everything goes down the drain. Somehow, she makes everything about himself. It started with benign teasing, but it might turn to mean and hurtful and might make you lose confidence in yourself slowly."));
    
  };

   if(userGroup=="Alpha 3 Female"){
    
    details.add(Details(image: "assets/images/humble_girl.png", title:"The Humble and Grounded Girl", desc:"The moment you set your eyes on her, you know she is not a pushover. She is grounded, self-assured and competent. You just met her and she tells you about her most secret vulnerabilities, making you feel you are special and she trusts you and therefore she gains her trust in return. She can be reflexively aggressive when the situation demands it."));
    details.add(Details(image: "assets/images/Dynamic_and_Purposeful_Girl.png", title:"The Dynamic Girl", desc:"She believes in hard work and can take responsibilities and get the job done. In extreme circumstances, she is composed, decisive and quick to react. She is always making plans and staying involved. She celebrates your achievements and helps you shine in the spotlight."));
    details.add(Details(image: "assets/images/charming_Girl.png", title:"The Charming Girl", desc:"Spending time with her is enriching and energising. She is confident and good natured under her hard exterior. She lets you be comfortable and sure in your truest self. When you talk, you are always her focus of attention, she listens and keeps secrets."));
    details.add(Details(image: "assets/images/charismatic_Girl.png", title:"The Charismatic Girl", desc:"She questions you and allows you to first speak, and tries to understand your thinking. As you get to know her deeper, you find that she might claim to know more than you, she rejects your opinions sometimes. She is good at spinning words. Her actions do not correspond to her words. Sometimes she never means what she is saying, she might also deny whenever she says something problematic."));
    details.add(Details(image: "assets/images/manipulative_girl.jpg", title:"The Manipulative Girl", desc:"Under the guise of joking, she makes rude inconsiderate statements. She constantly criticises you for the smallest things. With time, you will be affected by this constant nagging. If you even try to voice your concerns, she will lie to you or blame you, to make the friendship go on. She is sensitive to others feelings, but sometimes she might make dramatic baseless statements during confrontations, she might use your feelings against you."));
      
  };

  if(userGroup=="Alpha 4 Female"){
    
    details.add(Details(image: "assets/images/humble_girl.png", title:"The Humble and Grounded Girl", desc:"The moment you set your eyes on her, you know she is not a pushover. She is grounded, self-assured and competent. You just met her, she constantly texts you, showers attention, and she tells you about her most secret vulnerabilities, making you feel you are special and she trusts you and therefore she gains her trust in return. You might also want to make her happy."));
    details.add(Details(image: "assets/images/Dynamic_and_Purposeful_Girl.png", title:"The Dynamic Girl", desc:"She believes in hard work and can take responsibilities and get the job done. In extreme circumstances, she is composed, decisive and quick to react. She is a strategist, always making plans and staying involved. She always pursues compliments but lacks empathy for others in certain situations. She lets you be comfortable and sure in your truest self."));
    details.add(Details(image: "assets/images/charismatic_Girl.png", title:"The Charismatic Girl", desc:"She questions you and allows you to first speak, and tries to understand your thinking. As you get to know her deeper, you find that she might claim to know more than you, she rejects your opinions sometimes. SHe is good at spinning words. Her actions do not correspond to her words.Sometimes she never means what she is saying, she might also deny whenever she says something problematic."));
    details.add(Details(image: "assets/images/self_obssessed_Girl.png", title:"The Self Obsessed Girl", desc:"She thinks that she is always right and everything should be done according to her methods. Even if you know that it is her fault, she will never expect you to ask her to say sorry. If something happens which she does not approve of, everything goes down the drain. Somehow, she makes everything about himself. It started with benign teasing, but it might turn to mean and hurtful and might make you lose confidence in yourself slowly."));
    details.add(Details(image: "assets/images/manipulative_girl.jpg", title:"The Manipulative Girl", desc:"Under the guise of joking, she makes rude inconsiderate statements. She constantly criticises you for the smallest things. With time, you will be affected by this constant nagging. If you even try to voice your concerns, she will lie to you or blame you, to make the friendship go on. She is sensitive to others feelings, but sometimes she might make dramatic baseless statements during confrontations, she might use your feelings against you."));
       
  };

   if(userGroup=="Alpha 5 Female"){
    
    details.add(Details(image: "assets/images/charismatic_Girl.png", title:"The Charismatic Girl", desc:"It looks like she is very pleasant when you first meet her, so attentive. Her presence, trust and charisma disarm you. She is self-assured, competent and proud. She believes in hard work and doing the right thing. She is a person of well built opinions but always open to new experiences and mindsets. She is only trying to discover ways of gaining your confidence. If criticism is needed, she does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_girl.png", title:"The Smart Girl", desc:"She is honest and straightforward. She will always give you the facts as they are and wont twist them, even if it requires bluntness on their part. You never truly know what is happening in her brain, you are always left guessing. She believes that open honest conversations are the roots of a solid relationship. She might not open up in text about her internal feelings."));
    details.add(Details(image: "assets/images/Dynamic_and_Purposeful_Girl.png", title:"The Dynamic Girl", desc:"She celebrates your achievements and helps you shine in the spotlight. She values your opinions even if they may vary from her own. She does not shame you for your interests. Instead, she is your ally in all activities you wish to pursue. She makes plans with you. In extreme circumstances, she is composed, decisive and quick to react."));
    details.add(Details(image: "assets/images/charming_Girl.png", title:"The Charming Girl", desc:"Spending time with her is enriching and energising. She is confident and good natured under her hard exterior. She lets you be comfortable and sure in your truest self. When you talk, you are always her focus of attention, she listens. She makes you feel seen and validates you, but depending upon her moods too, she sometimes is quite unresponsive and her true emotions rarely appear."));
    details.add(Details(image: "assets/images/impulsive_girl.png", title:"The Impulsive Girl", desc:"After relations begin to lose, things start to shift. Her surprise ideas at the beginning now appear more impulsive. Sometimes she is late, and she either deflects or quotes work reasons if you question her where she was. She is also more upset, getting irritated for the smallest of reasons. She does not express guilt for her mistakes and faults, she never apologises. After every encounter, you are left slightly drained."));

  };

    if(userGroup=="Alpha 6 Female"){
    
    details.add(Details(image: "assets/images/charismatic_Girl.png", title:"The Charismatic Girl", desc:"It looks like she is very pleasant when you first meet her, so attentive. Her presence, trust and charisma disarm you. She is self-obsessed, competent and proud. She is a person of well built opinions but always open to new experiences and mindsets. She is only trying to discover ways of gaining your confidence and you might certainly want to make him happy. If criticism is needed, she does so with gentleness and patience."));
    details.add(Details(image: "assets/images/smart_girl.png", title:"The Smart Girl", desc:"She is honest and straightforward. She will always give you the facts as they are and wont twist them, even if it requires bluntness on their part. She constantly texts you, showers attention, makes you feel wanted. You never truly know what is happening in her brain, you are always left guessing. She values your opinions even if they may vary from her own. She might not open up in text about her internal feelings."));
    details.add(Details(image: "assets/images/Dynamic_and_Purposeful_Girl.png", title:"The Dynamic Girl", desc:"She celebrates your achievements and helps you shine in the spotlight. In extreme circumstances, she is composed, decisive and quick to react. Your issues and situations receive equal focus as her own, but depending upon her moods too, she sometimes is quite unresponsive and her true emotions rarely appear. Sometimes her emotions feel fake, she pretends that she is interested with your things and you do not feel seen or understood when you are with her."));
    details.add(Details(image: "assets/images/impulsive_girl.png", title:"The Impulsive Girl", desc:"After relations begin to lose, things start to shift. Her surprise ideas at the beginning now appear more impulsive. Sometimes she is late, and she either deflects or quotes work reasons if you question her where she was. She is also more upset, getting irritated for the smallest of reasons. She does not express guilt for her mistakes and faults, she never apologises. After every encounter, you are left slightly drained."));
    details.add(Details(image: "assets/images/self_obssessed_Girl.png", title:"The Self Obsessed Girl", desc:"She thinks that she is always right and everything should be done according to her methods. Even if you know that it is her fault, she will never expect you to ask her to say sorry. If something happens which she does not approve of, everything goes down the drain. Somehow, she makes everything about herself. It started with benign teasing, but it might turn to mean and hurtful and might make you lose confidence in yourself slowly."));
       
  };

   if(userGroup=="Alpha 7 Female"){
    
    details.add(Details(image: "assets/images/charismatic_Girl.png", title:"The Charismatic Girl", desc:"It looks like she is very pleasant when you first meet her, so attentive. Her presence, trust and charisma disarm you. She is self-assured, competent and proud. You just met her and she tells you about her most secret vulnerabilities, she questions you and allows you to first speak, and tries to understand your thinking, making you feel you are special and she trusts you and only for trying to discover ways of gaining your confidence."));
    details.add(Details(image: "assets/images/smart_girl.png", title:"The Smart Girl", desc:"She always claims to know more than you, she rejects your opinions sometimes. You never truly know what is happening in her brain, you are always left guessing. SHe is good at spinning words. Her actions do not correspond to her words. Sometimes she never means what she is saying; she might also deny whenever she says something problematic."));
    details.add(Details(image: "assets/images/Dynamic_and_Purposeful_Girl.png", title:"The Dynamic Girl", desc:"She celebrates your achievements and helps you shine in the spotlight. Your issues and situations receive equal focus as her own, but depending upon her moods too, she sometimes is quite unresponsive and her true emotions rarely appear. Sometimes her emotions feel fake, she pretends that she is interested with your things and you do not feel seen or understood when you are with her."));
    details.add(Details(image: "assets/images/impulsive_girl.png", title:"The Impulsive Girl", desc:"After relations begin to lose, things start to shift. Her surprise ideas at the beginning now appear more impulsive. Sometimes she is late, and she either deflects or quotes work reasons if you question her where she was. She is also more upset, getting irritated for the smallest of reasons. She does not express guilt for her mistakes and faults, she never apologises. After every encounter, you are left slightly drained."));
    details.add(Details(image: "assets/images/manipulative_girl.jpg", title:"The Manipulative Girl", desc:"Under the guise of joking, she makes rude inconsiderate statements. She constantly criticises you for the smallest things. With time, you will be affected by this constant nagging. If you even try to voice your concerns, she will lie to you or blame you, to make the friendship go on. She is sensitive to others feelings, but sometimes she might make dramatic baseless statements during confrontations, she might use your feelings against you."));
    
  };

   if(userGroup=="Beta 1 Female"){
    
    details.add(Details(image: "assets/images/mesmerising_girl.png", title:"The Mesmerising Girl", desc:"When you meet her, she is all in her own world. SHe is direct and efficient. She texts you firmly, compliments you, things begin to look like a fairy tale, making you feel wanted. This makes you want to keep pleasing her and everything is happy in paradise. She prioritises her goals and ambitions. She will always tell you the truth, even if it means being blunt."));
    details.add(Details(image: "assets/images/flamboyant_girl.png", title:"The Flamboyant Girl", desc:"She has strong beliefs but is always open to new experiences, she sees all the sides of every situation.  She asks your opinions while making important decisions and pays heed to your advice. She is direct with her thoughts on any ideas being discussed. Instead, she is your partner in all of your endeavours. She is an agreeable easy-going person and fun to be around."));
    details.add(Details(image: "assets/images/hotshot_girl.png", title:"The Hotshot Girl", desc:"She is calm, decisive, and fast in high-pressure situations. When speaking with her, you are always treated as an equal. She never disregards an idea outright if you present it to her but if it is against him then she constantly picks on you. This will begin with harmless teasing, but afterwards, It is mean and hurtful. She is constantly fishing for compliments. All conversations with her ends up becoming about her. It is always her achievements, her situations."));
    details.add(Details(image: "assets/images/narcissist_ girl.png", title:"The Narcissist Girl", desc:"While texting she may twist your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. She can not be handled in texting, to understand her you better have to hear her tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, she lash out and become aggressive. She may go as far as to destroy your reputation to save her own."));
    details.add(Details(image: "assets/images/gaslighter _girl.png", title:"The Gaslighter Girl", desc:"Gaslighting is her ultimate weapon, which brings down your self-esteem, thereby giving her an inflated sense of self. She believes she is right about everything. She will never be the one who apologises, even if you know it is her fault. When you are with her, you do not feel seen or understood. She will panic and try to fool you with kind words, promising you that she will change, become better."));

  };

   if(userGroup=="Beta 2 Female"){
    
    details.add(Details(image: "assets/images/mesmerising_girl.png", title:"The Mesmerising Girl", desc:"When you meet her, she is all in her own world. She is easy to talk to and has a pleasant attitude. She texts you firmly, compliments you. You have only just met her and five minutes later sHe is telling you her most secret vulnerabilities, making you believe you are special and that she trusts you. She asks you questions and lets you speak up first, trying to understand your mindset. She is the pacifist in any discussion. She consistently tries to be on the same page with you."));
    details.add(Details(image: "assets/images/flamboyant_girl.png", title:"The Flamboyant Girl", desc:"She is organised, focused and driven. She is an agreeable easy-going person and fun to be around. She congratulates you on your accomplishments as if they were her own and encourages you to do the same. She is empathic, which makes him an attentive listener and maintains honest relationships. She can adequately handle responsibilities and get the job done."));
    details.add(Details(image: "assets/images/hotshot_girl.png", title:"The Hotshot Girl", desc:"Also if you make a mistake, she does not chastise you for it. Instead, she will go to great efforts to assist you in resolving the issue. Sometimes she bullies you which can take varied forms, she always knows more than you. She will either lie and or push the blame on you, calling you �crazy�. She makes rude inconsiderate statements under the guise of I am kidding but, It is meant to cause offence. She denies she ever said something, even though you have proof."));
    details.add(Details(image: "assets/images/machiavelliant_girl.jpg", title:"The Machiavellian Girl", desc:"She criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through her teeth is second nature to them. Her actions do not match her words. During confrontations, she uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, she gives you the silent treatment. Even if you were not the one at fault, her silence shifts the weight of her behaviour on you. She excellently manipulates you, pulling your strings like a puppet, because she knows what makes you tick."));
    details.add(Details(image: "assets/images/imposter_girl.png", title:"The Imposter Girl", desc:"She is aware of the power of words and is cautious while using them. Her comments are presented in a kind tone. While texting she twists your words and plays with it, changing the narrative and easily manipulating you with texts. She spins your thoughts, taking them out of context. Every text you send feels like a step on thin ice. She can not be handled in texting, to understand her you better have to hear her tone of saying."));

  };

   if(userGroup=="Beta 3 Female"){
    
    details.add(Details(image: "assets/images/mesmerising_girl.png", title:"The Mesmerising Girl", desc:"When you meet her, she is all in her own world. She texts you firmly, compliments you, things begin to look like a fairy tale, making you feel wanted. This makes you want to keep pleasing her and everything is happy in paradise. You have only just met her and five minutes later sHe is telling you her most secret vulnerabilities, making you believe you are special and that she trusts you. She asks you questions and lets you speak up first, trying to understand your mindset."));
    details.add(Details(image: "assets/images/hotshot_girl.png", title:"The Hotshot Girl", desc:"She is organised, focused and driven. She is an agreeable easy-going person and fun to be around. She is an attentive listener and maintains honest relationships. Sometimes she bullies you which can take varied forms, she always knows more than you. She will either lie or push the blame on you, calling you crazy. She makes rude inconsiderate statements under the guise of I am kidding but, It is meant to cause offence. She denies she ever said something, even though you have proof."));
    details.add(Details(image: "assets/images/narcissist_ girl.png", title:"The Narcissist Girl", desc:"While texting she may twist your words and plays with it, changing the narrative and easily manipulating you with texts. She spins your thoughts, taking them out of context. Every text you send feels like a step on thin ice. She can not be handled in texting, to understand him you better have to hear her tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, she lash out and become aggressive, calling you names. She may go as far as to destroy your reputation to save her own."));
    details.add(Details(image: "assets/images/machiavelliant_girl.jpg", title:"The Machiavellian Girl", desc:"She criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through her teeth is second nature to them. Her actions do not match her words. During confrontations, she uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, she gives you the silent treatment. Even if you were not the one at fault, her silence shifts the weight of her behaviour on you. She excellently manipulates you, pulling your strings like a puppet, because she knows what makes you tick."));
    details.add(Details(image: "assets/images/gaslighter _girl.png", title:"The Gaslighter Girl", desc:"Gaslighting is her ultimate weapon, which brings down your self-esteem, thereby giving her an inflated sense of self. She believes she is right about everything. She will never be the one who apologises, even if you know it is her fault. When you are with her, you do not feel seen or understood. It feels like all she has is just you. She will panic and try to fool you with kind words, promising you that she will change, become better."));

  };

   if(userGroup=="Beta 4 Female"){
    
    details.add(Details(image: "assets/images/generous_girl.png", title:"The Generous Girl", desc:"When you first meet her, she seems like she is so charming, so attentive. She has strong beliefs but is always open to new experiences, she sees all the sides of every situation. In the beginning she can be a little difficult to talk to, but has a pleasant attitude. The relationship might, however, smooth out after that rocky stretch. She is the pacifist in any discussion. She listens to your viewpoints, even if they differ from her own, she is just trying to find ways to gain your trust."));
    details.add(Details(image: "assets/images/flamboyant_girl.png", title:"The Flamboyant Girl", desc:"There is a presence about her, her confidence, self-assuredness and charm disarm you. She pretends to be good natured, makes plans with you, makes you like her in the beginning. She congratulates you on your accomplishments as if they were her own and encourages you to do the same. You never really know what is going on in her head which always keeps you guessing. Once she is sure, you trust her completely, she becomes the parasite herself and you become her host."));
    details.add(Details(image: "assets/images/hotshot_girl.png", title:"The Hotshot Girl", desc:"She is aware of the power of words and is cautious while using them. Her comments are presented in a kind tone. While texting she twists your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. She can not be handled in texting, to understand her you better have to hear her tone of saying."));
    details.add(Details(image: "assets/images/proud_girl.png", title:"The Proud Girl", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes sHe is late and when you ask her where she was, she either deflects or cites work reasons. She also has these moods nowadays, her temper flying at the tiniest of reasons. Her earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. She shows no guilt over her mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/imposter_girl.png", title:"The Imposter Girl", desc:"She changes the subject when you ask more about her. Even after spending all this time, you never truly know what sHe is actually like. She is cold and inconsiderate to the feelings of other people around her. She lacks discipline and you feel like sHe is going down and dragging you with her. In the past, she says she has had multiple partners but none of them lasted long. She is receptive to your feedback and grateful for them."));

  };

   if(userGroup=="Beta 5 Female"){
    
    details.add(Details(image: "assets/images/generous_girl.png", title:"The Generous Girl", desc:"When you first meet her, she seems like she is so charming, so attentive. She texts you constantly, flatters you with compliments, things begin to look like a fairy tale, making you feel wanted. This makes you want to keep pleasing her and everything is happy in paradise. There is a presence about her, her confidence and charm disarm you. Once she is sure, you trust her completely, she becomes the parasite herself and you become her host."));
    details.add(Details(image: "assets/images/proud_girl.png", title:"The Proud Girl", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes sHe is late and when you ask him where she was, she either deflects or cites work reasons. She also has these moods nowadays, her temper flying at the tiniest of reasons. Her earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. She shows no guilt over her mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/imposter_girl.png", title:"The Imposter Girl", desc:"She changes the subject when you ask more about him. Even after spending all this time, you never truly know what sHe is actually like. She is cold and inconsiderate to the feelings of other people around her. She lacks discipline and you feel like sHe is going down and dragging you with her. In the past, she says she has had multiple partners but none of them lasted long. She is receptive to your feedback and grateful for them."));
    details.add(Details(image: "assets/images/narcissist_ girl.png", title:"The Narcissist Girl", desc:"While texting she twists your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. She can not be handled in texting, to understand her you better have to hear her tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, she lash out and become aggressive, calling you names. She may go as far as to destroy your reputation to save her own."));
    details.add(Details(image: "assets/images/gaslighter _girl.png", title:"The Gaslighter Girl", desc:"Gaslighting is her ultimate weapon, which brings down your self-esteem, thereby giving her an inflated sense of self. She believes she is right about everything. She will never be the one who apologises, even if you know it is her fault. When you are with her, you do not feel seen or understood. It feels like all she has is just you. She will panic and try to fool you with kind words, promising you that she will change, become better."));

  };

   if(userGroup=="Beta 6 Female"){
    
    details.add(Details(image: "assets/images/generous_girl.png", title:"The Generous Girl", desc:"When you first meet her, she seems like she is so charming, so attentive. She is easy to talk to and has a pleasant attitude. She flatters you with compliments. You have only just met her and five minutes later sHe is telling you her most secret vulnerabilities, making you believe you are special and that she trusts you, she is just trying to find ways to gain your trust. She asks you questions and lets you speak up first, trying to understand your mindset."));
    details.add(Details(image: "assets/images/flamboyant_girl.png", title:"The Flamboyant Girl", desc:"There is a presence about her, her confidence, self-assuredness and charm disarm you. She pretends to be good natured, makes plans with you, makes you like her in the beginning. She congratulates you on your accomplishments as if they were her own and encourages you to do the same. You never really know what is going on in her head which always keeps you guessing. Once she is sure, you trust her completely, she becomes the parasite himself and you become her host."));
    details.add(Details(image: "assets/images/proud_girl.png", title:"The Proud Girl", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes sHe is late and when you ask her where she was, she either deflects or cites work reasons. She also has these moods nowadays, her temper flying at the tiniest of reasons. Her earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. She shows no guilt over her mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/imposter_girl.png", title:"The Imposter Girl", desc:"She changes the subject when you ask more about her. Even after spending all this time, you never truly know what sHe is actually like. She is cold and inconsiderate to the feelings of other people around her. She lacks discipline and you feel like sHe is going down and dragging you with her. In the past, she says she has had multiple partners but none of them lasted long. She is receptive to your feedback and grateful for them."));
    details.add(Details(image: "assets/images/machiavelliant_girl.jpg", title:"The Machiavellian Girl", desc:"She criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through her teeth is second nature to them. Her actions do not match her words. During confrontations, she uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, she gives you the silent treatment. Even if you were not the one at fault, her silence shifts the weight of her behaviour on you. She excellently manipulates you, pulling your strings like a puppet, because she knows what makes you tick."));

  };

   if(userGroup=="Beta 7 Female"){
    
    details.add(Details(image: "assets/images/generous_girl.png", title:"The Generous Girl", desc:"When you first meet her, she seems like she is so charming, showering you with attention. She texts you constantly, flatters you with compliments, things begin to look like a fairy tale, making you feel wanted and everything is happy in paradise. You have only just met her and five minutes later sHe is telling you her most secret vulnerabilities, she asks you questions and lets you speak up first, making you believe you are special, she is just trying to find ways to gain your trust. Once she is sure, you trust her completely, she becomes the parasite himself and you become her host."));
    details.add(Details(image: "assets/images/proud_girl.png", title:"The Proud Girl", desc:"But things eventually begin to change. The confidence, which was impressive at first, now feels like arrogance. Sometimes sHe is late and when you ask him where she was, she either deflects or cites work reasons. She also has these moods nowadays, her temper flying at the tiniest of reasons. Her earlier surprising plans now seem more impulsive. Some plans end up getting cancelled just as quickly as they were made. She shows no guilt over her mistakes and wrong actions, never apologises."));
    details.add(Details(image: "assets/images/machiavelliant_girl.jpg", title:"The Machiavellian Girl", desc:"She criticises you constantly for the smallest of things, pitting your insecurities against you. Twisting facts and lying through her teeth is second nature to them. Her actions do not match her words. During confrontations, she uses your feelings against you, makes dramatic statements, ultimatums to put you on the spot. After a confrontation, she gives you the silent treatment. Even if you were not the one at fault, her silence shifts the weight of her behaviour on you. She excellently manipulates you, pulling your strings like a puppet, because she knows what makes you tick."));
    details.add(Details(image: "assets/images/narcissist_ girl.png", title:"The Narcissist Girl", desc:"While texting she twists your words and plays with it, changing the narrative and easily manipulating you with texts. Every text you send feels like a step on thin ice. She can not be handled in texting, to understand her you better have to hear her tone of saying. At one point, you will have had enough and want to call things off. All this feels so real, but it is all an act. And if you stand firm on your decision of calling it quits, she lash out and become aggressive, calling you names. She may go as far as to destroy your reputation to save her own."));
    details.add(Details(image: "assets/images/gaslighter _girl.png", title:"The Gaslighter Girl", desc:"Gaslighting is her ultimate weapon, which brings down your self-esteem, thereby giving her an inflated sense of self. She believes she is right about everything. She will never be the one who apologises, even if you know it is her fault. When you are with her, you do not feel seen or understood. It feels like all she has is just you. She will panic and try to fool you with kind words, promising you that she will change, become better."));

  };
 
  return details;
  

}

class Data{
  String currentUserGroup;
  String currentUserGender;
  String otherUserGroup;
  String otherUserGender;
  Data({required this.currentUserGender,required this.currentUserGroup,required this.otherUserGender,required this.otherUserGroup});

  List<Details> getDescription(){
    print(otherUserGender);
    print( otherUserGroup);
    List<Details> description=[];
      if(otherUserGender=="Male"){
        switch(otherUserGroup){
          case "Alpha 1":description=describeData("Alpha 1 Male");
          break;
          case "Alpha 2":description=currentUserGroup=="Alpha 2" ?
          describeData("Alpha 1 Male") : describeData("Alpha 2 Male");
          break;
          case "Alpha 3":description=currentUserGroup=="Alpha 3" ?
          describeData("Alpha 1 Male") : describeData("Alpha 3 Male");
          break;
          case "Alpha 4":description=currentUserGroup=="Alpha 4" ?
          describeData("Alpha 1 Male") : describeData("Alpha 4 Male");
          break;
          case "Alpha 5":description=currentUserGroup=="Alpha 5" ?
          describeData("Alpha 1 Male") : describeData("Alpha 5 Male");
          break;
          case "Alpha 6":description=currentUserGroup=="Alpha 6" ?
          describeData("Alpha 1 Male") : describeData("Alpha 6 Male");
          break;
          case "Alpha 7":description=currentUserGroup=="Alpha 7" ?
          describeData("Alpha 1 Male") : describeData("Alpha 7 Male");
          break;
          case "Beta 1":description=currentUserGroup=="Beta 1" ?
          describeData("Alpha 1 Male") : describeData("Beta 1 Male");
          break;
          case "Beta 2":description=currentUserGroup=="Beta 2" ?
          describeData("Alpha 1 Male") : describeData("Beta 2 Male");
          break;
          case "Beta 3":description=currentUserGroup=="Beta 3" ?
          describeData("Alpha 1 Male") : describeData("Beta 3 Male");
          break;
          case "Beta 4":description=currentUserGroup=="Beta 4" ?
          describeData("Alpha 1 Male") : describeData("Beta 4 Male");
          break;
          case "Beta 5":description=currentUserGroup=="Beta 5" ?
          describeData("Alpha 1 Male") : describeData("Beta 5 Male");
          break;
          case "Beta 6":description=currentUserGroup=="Beta 6" ?
          describeData("Alpha 1 Male") : describeData("Beta 6 Male");
          break;
          case "Beta 7":description=currentUserGroup=="Beta 7" ?
          describeData("Alpha 1 Male") : describeData("Beta 7 Male");
          break;
        }
      }
      else if(otherUserGender=="Female"){
        switch(otherUserGroup){
          case "Alpha 1":description=describeData("Alpha 1 Female");
          break;
          case "Alpha 2":description=currentUserGroup=="Alpha 2" ?
          describeData("Alpha 1 Female") : describeData("Alpha 2 Female");
          break;
          case "Alpha 3":description=currentUserGroup=="Alpha 3" ?
          describeData("Alpha 1 Female") : describeData("Alpha 3 Female");
          break;
          case "Alpha 4":description=currentUserGroup=="Alpha 4" ?
          describeData("Alpha 1 Female") : describeData("Alpha 4 Female");
          break;
          case "Alpha 5":description=currentUserGroup=="Alpha 5" ?
          describeData("Alpha 1 Female") : describeData("Alpha 5 Female");
          break;
          case "Alpha 6":description=currentUserGroup=="Alpha 6" ?
          describeData("Alpha 1 Female") : describeData("Alpha 6 Female");
          break;
          case "Alpha 7":description=currentUserGroup=="Alpha 7" ?
          describeData("Alpha 1 Female") : describeData("Alpha 7 Female");
          break;
          case "Beta 1":description=currentUserGroup=="Beta 1" ?
          describeData("Alpha 1 Female") : describeData("Beta 1 Female");
          break;
          case "Beta 2":description=currentUserGroup=="Beta 2" ?
          describeData("Alpha 1 Female") : describeData("Beta 2 Female");
          break;
          case "Beta 3":description=currentUserGroup=="Beta 3" ?
          describeData("Alpha 1 Female") : describeData("Beta 3 Female");
          break;
          case "Beta 4":description=currentUserGroup=="Beta 4" ?
          describeData("Alpha 1 Female") : describeData("Beta 4 Female");
          break;
          case "Beta 5":description=currentUserGroup=="Beta 5" ?
          describeData("Alpha 1 Female") : describeData("Beta 5 Female");
          break;
          case "Beta 6":description=currentUserGroup=="Beta 6" ?
          describeData("Alpha 1 Female") : describeData("Beta 6 Female");
          break;
          case "Beta 7":description=currentUserGroup=="Beta 7" ?
          describeData("Alpha 1 Female") : describeData("Beta 7 Female");
          break;
        }

      }
    return description;
  }
}
